name: admin_api_types
description: The types used by the Admin API.
version: 1.0.0

environment:
  sdk: "^3.10.0"

resolution: workspace

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.2
  json_serializable: ^6.11.1
  very_good_analysis: ^10.0.0
