name: admin_api_types
description: The types used by the Admin API.
version: 1.0.0

environment:
  sdk: "^3.9.0"

resolution: workspace

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  very_good_analysis: ^9.0.0
