name: enmeshed
publish_to: none

repository: https://github.com/nmshd/backbone
homepage: https://enmeshed.eu

environment:
  sdk: ">=3.5.0 <4.0.0"

dev_dependencies:
  melos: ^6.1.0
  very_good_analysis: ^7.0.0
