name: Check Pull Request

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  validate-pr-label:
    name: Validate the Pull Request's labels
    runs-on: ubuntu-latest
    steps:
      - name: PR must be labeled
        uses: jesusvasquez333/verify-pr-label-action@v1.4.0
        with:
          disable-reviews: true
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "breaking-change, bug, chore, ci, dependencies, documentation, enhancement, refactoring, test"
