name: Publish Admin UI Container Image

on:
  push:
    tags:
      - "aui/*"

jobs:
  publish-aui-container-image:
    name: Publish Admin UI Container Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install script dependencies
        run: npm install --prefix ./.ci
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version from git tag
        id: extract-version-from-git-tag
        run: echo "VERSION=$(./.ci/extractVersionFromGitTag.js)" >> $GITHUB_OUTPUT
        env:
          GIT_TAG: ${{ github.ref_name }}
      - name: Build Image
        run: ./.ci/aui/buildContainerImage.js
        env:
          TAG: ${{ steps.extract-version-from-git-tag.outputs.VERSION }}
      - name: Push Image
        run: ./.ci/aui/pushContainerImage.js
        env:
          TAG: ${{ steps.extract-version-from-git-tag.outputs.VERSION }}
